### ISSUE TITLE
Windows 10 support?

### ISSUE THREAD

**Issue by jsvini** [ryanries/UniversalPauseButton#1]
It doesn't work on Windows 10 (Build 10130)

**Comment by ryanries** [comment]
Odd... I don't currently have a Windows 10 machine to test with, but I have a spare machine that I could install it on.

**Comment by vovkkk** [comment]
Doesn’t work on 8.1 (Enterprise x32) either.
Is it 64bit only?
It just says app can’t be launched, ask publisher about version for this PC.

![2015-06-11 14-01-13](https://cloud.githubusercontent.com/assets/1975298/8102660/9c410d3a-1043-11e5-8a66-dfc2dbe6370b.png)

**Comment by ryanries** [comment]
It works in Windows 10.
