### ISSUE TITLE
Run Without Windows shell

### ISSUE THREAD

**Issue by xbrunox76** [ryanries/UniversalPauseButton#14]
Hello and congratulations for your very useful program.
I need to make it work on a Win7 64 bit machine that I don't load the shell on and therefore it doesn't load the taskbar. unfortunately the program does not start because it says that it cannot create the icon on the taskbar. Is there a solution?

**Comment by ryanries** [comment]
@xbrunox76 I have implemented your request in the latest release v1.1.5. Please see the updated readme. Better late than never, right?
