### ISSUE TITLE
Closing Doesnt Close the Program

### ISSUE THREAD

**Issue by SamHadavi** [ryanries/UniversalPauseButton#16]
When you click on the icon to exit the program, it disappears from the task bar but stays on task manager.

**Comment by MaximusX800** [comment]
This is definitely the case, any chance we could get a fix for this?

**Comment by ryanries** [comment]
Working on it. Haven't touched this project in over 5 years. :)

**Comment by MaximusX800** [comment]
Thank you very much!

**Comment by ryanries** [comment]
Please try the latest version, v1.0.4, which you can find in the "Releases" section. Let me know if this fixes the issue. Thanks!
