### ISSUE TITLE
"OpenProcess failed!" when trying to pause Diablo II

### ISSUE THREAD

**Issue by tomasz1986** [ryanries/UniversalPauseButton#18]
I like the pause button idea very much, but unfortunately this is what happens when trying to pause Diablo II (the original, not Resurrected).

![image](https://user-images.githubusercontent.com/5626656/180603589-85479407-72c3-4088-a7c6-5cf0782fa542.png)

**Comment by ryanries** [comment]
Likely a permissions issue. Try running UniversalPauseButton As Administrator. If that doesn't work, then it's likely Diablo II has some sort of anti-cheat tech in it that is preventing UniversalPauseButton from calling OpenProcess on it.
