### ISSUE TITLE
Feature Request - Specify a window/app to pause/unpause instead of active window

### ISSUE THREAD

**Issue by JReming85** [ryanries/UniversalPauseButton#20]
Hi there,

Loving the program so far and seems to be better then my previous setup of using Cheat Engine to pause the process or set the speed to 0.01

However could you possible add a new feature to add a hotkey to suspend a predefined window/application?

I mainly use this for gaming, and I generally use a controller while also not having the game window as active.. (browsing web, watching videos or anime, etc) and would like to just pause without needing to click back into the game.

Think this is a feature you would be interested in implementing?

**Comment by ryanries** [comment]
@rickylford @JReming85 Better late than never, right?  I have added this feature in the latest release v1.1.5. Please see the updated readme.
