### ISSUE TITLE
My registry only showing one file

### ISSUE THREAD

**Issue by azulaisasnack** [ryanries/UniversalPauseButton#21]
Hello my registry is only showing one file, I've tried to right-click and add my own dword etc. to customize a pause button but that's not working either. I have to reprogram my button because my laptop doesn't have a pause button. Thanks, I hope I can get this to work, BG 3 not letting me pause cut scenes is killing me! 
![Screenshot 2023-09-07 155031](https://github.com/ryanries/UniversalPauseButton/assets/144395250/b3cbd2d9-eff2-4f8a-b93e-5f7a65e06319)

**Comment by ryanries** [comment]
Right, the registry settings don't exist by default, you have to create them manually.
After you create the registry setting and set it to your preferred value, you need to restart UniversalPauseButton.

**Comment by ryanries** [comment]
Did you figure it out yet? If not could you enable Debug as per the instructions in the readme and show me the debug output?

**Comment by azulaisasnack** [comment]
Apologies I did not and didn't want to bother you any further! I will try again tonight. The issue I was having was even when I was using the default virtual key code it was creating a strange value, but I will try again tonight I may have missed something.

**Comment by ryanries** [comment]
Let me know if you still need help on this, otherwise I am closing this issue
