### ISSUE TITLE
Can't find the registry files to edit (WIN10 & 11)

### ISSUE THREAD

**Issue by Aboodal3deny** [ryanries/UniversalPauseButton#25]
I've downloaded both 1.1.5 and 1.0.4 versions of the app. I tried the latest version and when it didn't seem to work, I tried the older version but neither seemed to give me the "files" in the registry editor. I tried in both of my computers: win10 and 11.

Sorry if this is a newbie question, I don't know how to exactly use this site. I found this app on a language learning community since I want to learn Chinese as I'm playing Red Dead Redemption 2 by pausing subtitles.
![image_2023-12-24_151306385](https://github.com/ryanries/UniversalPauseButton/assets/59121398/1c124859-d3b5-475e-a1ba-48b3318d6727)

Lenovo Laptop specs:
Win11
RTX 3060
8 GB 
Intel i7-12650

PC specs:
RTX 2070 Super
32 GB 
Ryzen 7 3700x

EDIT: PC is win10

**Comment by xAJx1383** [comment]
it seems you didnt define a Process Name to pause, i think you could find the process name by going to details in task manager and copy the name of target process to pause and add it to that Registery directory.
use this .reg file and just change game.exe to the process name and then run it
[RegisterGameToPause.zip](https://github.com/ryanries/UniversalPauseButton/files/13803929/RegisterGameToPause.zip)

**Comment by Aboodal3deny** [comment]
> it seems you didnt define a Process Name to pause, i think you could find the process name by going to details in task manager and copy the name of target process to pause and add it to that Registery directory. use this .reg file and just change game.exe to the process name and then run it [RegisterGameToPause.zip](https://github.com/ryanries/UniversalPauseButton/files/13803929/RegisterGameToPause.zip)
> 
> make sure to restart program if its already started and if it didnt work run the program as admin

Hi AJ, thank you so much for the response. The problem was that I didn't know that I needed to create those registry files and specify their type myself. I thought that, by running UniversalPauseButton, these registry files are gonna be made.
It works now but not with RDR2. However, thanks to that last line of yours, that fixed the issue. Thanks so much, you're a lifesaver.
