### ISSUE TITLE
x64 Versions Don't Work

### ISSUE THREAD

**Issue by jamolnng** [ryanries/UniversalPauseButton#3]
I compiled the x64 versions for Windows 7 SP1 using VS2013 Community and while they run they do not work. I have very little experience with the Windows API so I'm not sure why it would be that way.

**Comment by ryanries** [comment]
Interesting... I only compiled the x64 version myself... I haven't even tested the 32-bit version. Could you clarify what you mean exactly by "do not work?"  Does it compile?

**Comment by jamolnng** [comment]
Compiles fine and runs and the icon shows in the system tray but when I press the break/pause button nothing happens and when I click on the icon in the system tray nothing happens. The 32-bit version works fine for me though.

**Comment by jamolnng** [comment]
Well now of course that I go and compile it again it works. Not sure what the issue is but it works now.
