### ISSUE TITLE
[Feature Request] Allow customizing the key used for pausing

### ISSUE THREAD

**Issue by guiniol** [ryanries/UniversalPauseButton#5]
Currently I have to recompile the program if I want to change the key used to pause applications (I don't have a "pause" button on this keyboard)
It would be nice if users could configure that (even if it's just a text file to edit) but I have no idea how much work that would require.

Thanks for this application in any case. I have had the exact same problem you had way too many times.

Cheers

**Comment by ryanries** [comment]
Should be taken care of now with the new settings.txt file.

**Comment by guiniol** [comment]
Thanks, that's great!
